version: "2"

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - revive
    - gofmt
    - goimports
    - unparam
    - bodyclose
    - misspell
    - godot

  settings:
    revive:
      rules:
        - name: exported
          severity: warning

issues: {}
